### ISSUE TITLE
configure_esp_secure_cert different device naming than espefuse for esp32s3

### ISSUE THREAD

**Issue by liliumjsn** [espressif/esp_secure_cert_mgr#5] opened 2022-11-08 10:25 UTC
Device naming is different between espefuse and configure_esp_secure_cert for esp32s3.
espefuse uses: "esp32s3beta2"
configure_esp_secure_cert uses: "esp32s3"

configure_esp_secure_cert error message:
`espefuse: error: argument --chip/-c: invalid choice: 'esp32s3' (choose from 'auto', 'esp32', 'esp32s2', 'esp32s3beta2', 'esp32c3')`

**Comment by AdityaHPatwardhan** [comment] 2022-11-16 03:17
Hi @liliumjsn,
Can you tell me what is the espefuse.py version at your end ?
You can get more info about the version by executing `espefuse.py -h` ( This would work from anywhere if esptool component has been added in the PATH)

**Comment by liliumjsn** [comment] 2022-11-16 09:53
It seems that this issue refers to an older version of espefuse.py. I can confirm that there is wrong naming in espefuse.py v3.0, and correct naming in espefuse.py v4.2.1.

**Comment by AdityaHPatwardhan** [comment] 2022-11-16 10:01
@liliumjsn If the problem is with earlier versions then I think that might be due to the the esp32s3 chip name at that time. If it works for you with `latest espefuse.py version` then I think it should be okay.

**Comment by AdityaHPatwardhan** [comment] 2022-11-17 09:17
Closing the issue since the query seems to have been resolved. Please feel free to re-open if it is not the case.
Thanks,
Aditya

**Closed as completed by AdityaHPatwardhan** 2022-11-17 09:17 UTC
